import { subDays, addDays } from 'date-fns';
import { Task } from '../types/task';

export const demoTasks: Task[] = [
  {
    id: 't1',
    title: 'Üniversite ödev taslağı',
    description: 'Sosyoloji dersi için literatür taraması bölümünü tamamla.',
    category: 'Akademik',
    priority: 'high',
    dueDate: addDays(new Date(), 1).toISOString(),
    dueTime: '18:00',
    createdAt: subDays(new Date(), 2).toISOString(),
    updatedAt: subDays(new Date(), 2).toISOString(),
    completed: false,
  },
  {
    id: 't2',
    title: 'Akşam antrenmanı',
    description: '45 dakikalık güç ve mobilite rutini.',
    category: 'Sağlık',
    priority: 'medium',
    dueDate: new Date().toISOString(),
    dueTime: '20:30',
    createdAt: subDays(new Date(), 1).toISOString(),
    updatedAt: subDays(new Date(), 1).toISOString(),
    completed: false,
  },
  {
    id: 't3',
    title: 'Kitaptan 30 sayfa oku',
    category: 'Okuma',
    priority: 'low',
    dueDate: addDays(new Date(), 4).toISOString(),
    createdAt: subDays(new Date(), 3).toISOString(),
    updatedAt: subDays(new Date(), 3).toISOString(),
    completed: false,
  },
  {
    id: 't4',
    title: 'Haftalık market alışverişi',
    description: 'Taze sebze, zeytinyağı, yoğurt, kahve çekirdeği.',
    category: 'Kişisel',
    priority: 'medium',
    dueDate: subDays(new Date(), 1).toISOString(),
    createdAt: subDays(new Date(), 4).toISOString(),
    updatedAt: subDays(new Date(), 4).toISOString(),
    completed: false,
  },
  {
    id: 't5',
    title: 'Proje kilometre taşı planlama',
    description: 'Yol haritasını gözden geçir ve sonraki sprint için iş paketlerine böl.',
    category: 'İş',
    priority: 'high',
    dueDate: addDays(new Date(), 6).toISOString(),
    dueTime: '10:00',
    createdAt: subDays(new Date(), 5).toISOString(),
    updatedAt: subDays(new Date(), 5).toISOString(),
    completed: true,
  },
];
